# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
  
  <img src="https://source.unsplash.com/320x240/?kitten,cat,dog,puppy"/>

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸš€Congrats on merging your first pull request!ğŸš€ ğŸ˜¹We are very proud of you!ğŸ˜¹

# It is recommend to include as many gifs and emojis as possible

